### ISSUE TITLE
FLIF in `ar` archives

### ISSUE THREAD

**Issue by panicbit** [FLIF-hub/FLIF-doc#5]
It seems the reference decoder supports FLIF inside of `ar` archives. Is that something that should be part of the spec? Should decoders support this? Or is that just some legacy code?

**Comment by jonsneyers** [comment]
I think it shouldn't be part of the spec; it's what I originally proposed to use to store metadata, but that has been superseded by the current metadata mechanism. So it's legacy code, and could probably be removed from the reference decoder (though I see no urgent reason to do so).

**Comment by panicbit** [comment]
Ok :+1:
